### ISSUE TITLE
scatter local variable not found

### ISSUE THREAD

**Issue by pkaleta** [dnanexus/dxWDL#240] opened 2019-05-06 12:30 UTC
@orodeh

This construct used to work in the previous version of dxWDL. Were local scatter vars deprecated or is there a bug somewhere in the compiler?

```
    scatter(bam in bwa.bam) {
        String lane = sub(sub(basename(bam), "_[AGTC]+_1.bam", ""), "s_", "")
        if (lane == "1") {
            File bam_lane1 = bam
        }
        if (lane == "2") {
            File bam_lane2 = bam
        }
    }
    Array[File] lane1_bams = select_all(bam_lane1)
```

The error is:

```
Block Vector(5) to execute:
scatter (bam in bwa.bam) {
  if ((lane == "2")) {
    bam_lane2 =  bam
  }
  lane =  sub(sub(basename(bam), "_[AGTC]+_1.bam", ""), "s_", "")
  if ((lane == "1")) {
    bam_lane1 =  bam
  }
}
lane2_bams =  select_all(bam_lane2)
call noop as noop_bams_by_lane { input: in = lane2_bams[0] }
java.lang.Exception: Failed to evaluate expression (lane == "2")
Errors:
NonEmptyList(ValueEvaluator[IdentifierLookup]: No suitable input for 'lane' amongst {bwa.bam, bam})
```

So this looks like the ordering of statements got changed somewhere in between, which is causing the `lane` to be undefined when executing first `if` statement.

**Comment by orodeh** [comment] 2019-05-06 20:09
This is a bug.

**Comment by orodeh** [comment] 2019-05-07 16:41
The problem is that converting to WOM causes source information to be lost. The original straight line program becomes a graph. Care is needed to maintain dependencies during expression evaluation, and there was a case where this wasn't done.

**Comment by orodeh** [comment] 2019-05-07 17:09
Fixed in master branch.

**Closed by orodeh** 2019-05-07 17:09 UTC
