### ISSUE TITLE
WDL parsing issue

### ISSUE THREAD

**Issue by mckinsel** [dnanexus/dxWDL#95] opened 2018-01-12 15:41 UTC
Hey, I'm getting a WDL parsing error for this WDL using dxWDL 0.57: 
```
task CountLines {
  File input_file

  command <<<
    wc -l ${input_file} | awk '{print $1}' > line.count
  >>>

  output {
    Int line_count = read_int("line.count")
  }
}

workflow CountLinesWorkflow {
  File input_file

  call CountLines {
    input: input_file=input_file
  }

  output {
    Int line_count=CountLines.line_count
  }
}
```

This is the error from dxWDL:
```
wdl4s.parser.WdlParser$SyntaxError: Unrecognized token on line 4, column 42:

    wc -l ${input_file} | awk '{print $1}' > line.count
                                         ^
        at wdl4s.parser.WdlParser.unrecognized_token(WdlParser.java:6972)
        at wdl4s.parser.WdlParser.lex(WdlParser.java:7045)
        at wdl4s.wdl.AstTools$.getAst(AstTools.scala:187)
        at wdl4s.wdl.WdlNamespace$.$anonfun$load$1(WdlNamespace.scala:179)
        at scala.util.Try$.apply(Try.scala:209)
        at wdl4s.wdl.WdlNamespace$.load(WdlNamespace.scala:179)
        at wdl4s.wdl.WdlNamespace$.loadUsingSource(WdlNamespace.scala:175)
        at dxWDL.Main$.washNamespace(Main.scala:323)
        at dxWDL.Main$.compileIR(Main.scala:498)
        at dxWDL.Main$.compile(Main.scala:599)
        at dxWDL.Main$.dispatchCommand(Main.scala:774)
        at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:819)
        at dxWDL.Main$delayedInit$body.apply(Main.scala:16)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at dxWDL.Main$.main(Main.scala:16)
        at dxWDL.Main.main(Main.scala)
```
I can fix it if I define variables `lbrace='{' rbrace='}'` and use those variables in the awk command, so there is a workaround. The weird thing is that this WDL passes validation with `wdltool-0.14`, and I thought both tools were using the same version of `wdl4s`, [version 0.15](https://github.com/broadinstitute/wdltool/blob/5a3741ec69b7cee069a4b9949679835a3261b5a3/build.sbt#L11). Any thoughts on what the problem could be?

**Comment by orodeh** [comment] 2018-01-12 20:01
Hmm. I reproduced the problem. Something is going wrong when I pretty print the workflow, and reload it.  I'll put it on my TODO list.

**Comment by orodeh** [comment] 2018-01-12 21:41
@mckinsel The problem is that when I pretty print the applet, I replace the `<<<`, `>>>` pair with curly brackets. It will be fixed in the upcoming release (0.58).

**Comment by mckinsel** [comment] 2018-01-16 17:25
Hey thanks @orodeh. Do you think this behavior is vague in the WDL spec? I can submit an issue to openwdl.

**Comment by orodeh** [comment] 2018-01-16 17:29
@mckinsel It is actually quite subtle.  

The problem has to do with the implementation, not the specification. The wdl4s library omits the brace symbol (`{` or `<<<`) when parsing the task. When I pretty-print the task, something wdl4s never does, I need to guess the brace symbol. My code doesn't always get it right, which is the source of the bug.

**Comment by orodeh** [comment] 2018-01-17 20:32
@mckinsel I think release [0.58](https://github.com/dnanexus/dxWDL/releases/tag/0.58) fixes this problem.

**Comment by orodeh** [comment] 2018-02-28 18:41
Fixed.

**Closed by orodeh** 2018-02-28 18:41 UTC
