### ISSUE TITLE
Seemingly incorrect compilation of applets

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dxWDL#225] opened 2019-04-22 18:35 UTC
I’m in the midst of debugging a complex workflow in transition to dxWDL 1.01.   In the course of that, I got a weird exception during applet compilation that I wanted to bring forward. I made it into the most minimal example I could:

```
==> outer.wdl <==
version 1.0

import "inner.wdl" as inner

workflow example {
    input {
        String lane
    }

    call inner.example_inner {
        input:
            lane=lane
    }
    output {
        String o = lane
    }
}

==> inner.wdl <==
version 1.0

workflow example_inner {
    input {
        String lane
    }

    output {
        String blah = lane
    }
}
```
 Generates this traceback:

```
project ID: project-FJF5zyj0vZJ72Vq6BQF5Zq54
folder: /deleteme
IR pass
  tasks=Set()
  sortByDependencies List(example, example_inner)
    depOrder =Vector(example_inner, example)
  compiling workflow example_inner
  Assembling workflow backbone example_inner
  compiling workflow example
  Compiling common applet example_common
  Assembling workflow backbone example
    Compiling call example_inner as stage
  inputVars=Vector(CVar(lane,WomStringType,None))
  allCallables=List(example_inner, example_common, example_outputs, example)
  allCallablesSorted=Vector(example_inner, example_common, example_outputs, example)
Looking for asset-id in dxWDL://releases/1.01
The asset dxWDLrt is from a different project project-F2gg1xj0KFB7BqB65QJG3GY3
The project already has a record pointing to asset dxWDLrt
Found 20 applets and 3 workflows in project-FJF5zyj0vZJ72Vq6BQF5Zq54 folder=/deleteme (12256 millisec)
Native pass, generate dx:applets and dx:workflows
[<ts>] InvalidInput: Expected the "outputs.outputSource" field of output parameter "blah" to be a $dnanexus_link referencing a stage output field. Code: 422 Request ID: <ts>-377714
InvalidInput: Expected the "outputs.outputSource" field of output parameter "blah" to be a $dnanexus_link referencing a stage output field
	at com.dnanexus.exceptions.DXAPIException$ApiExceptionClass$3.generateException(DXAPIException.java:45)
	at com.dnanexus.exceptions.DXAPIException.getInstance(DXAPIException.java:125)
	at com.dnanexus.DXHTTPRequest.requestImpl(DXHTTPRequest.java:421)
	at com.dnanexus.DXHTTPRequest.request(DXHTTPRequest.java:258)
	at com.dnanexus.DXAPI.workflowNew(DXAPI.java:37289)
	at dxWDL.compiler.Native.buildWorkflow(Native.scala:878)
	at dxWDL.compiler.Native.buildWorkflowIfNeeded(Native.scala:900)
	at dxWDL.compiler.Native.$anonfun$apply$1(Native.scala:927)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at dxWDL.compiler.Native.apply(Native.scala:914)
	at dxWDL.compiler.Top.compileNative(Top.scala:109)
	at dxWDL.compiler.Top.apply(Top.scala:246)
	at dxWDL.Main$.compile(Main.scala:420)
	at dxWDL.Main$.dispatchCommand(Main.scala:675)
	at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:732)
	at dxWDL.Main$delayedInit$body.apply(Main.scala:11)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at dxWDL.Main$.main(Main.scala:11)
	at dxWDL.Main.main(Main.scala)
```

**Comment by orodeh** [comment] 2019-04-22 23:14
The problem is that the script is passing a workflow input directly to a workflow output. I thought this was legal, however, it seems to be causing a platform platform. Meanwhile, a workaround is to pass the workflow input `lane` to a stage, and then passing that to the `inner` output. 

For example, this compiles: 

```
version 1.0

import "inner.wdl" as lib

workflow outer {
    input {
	String lane
    }

    call lib.inner as inner {
        input: lane=lane
    }

    output {
	String o = inner.blah
    }
}

----------

version 1.0

workflow inner {
    input {
        String lane
    }

    String tmp = lane

    output {
        String blah = tmp
    }
}
```

**Comment by jtratner** [comment] 2019-04-23 01:47
Ah that's helpful!  I tested a little more and it looks like this is also resolved by forcing dxWDL to generate an `outputs` applet by doing some magic in outputs.  Perhaps the fix (if you want to do it) is to have the compiler identify "subworkflow call to workflow output" as requiring the creation of an `outputs` applet?

**Comment by orodeh** [comment] 2019-04-25 18:40
I believe this is the same bug as #224. This is fixed in master.

**Closed by orodeh** 2019-04-25 18:40 UTC
