### ISSUE TITLE
Container ID ProjectName must start with project- or container-

### ISSUE THREAD

**Issue by pkaleta** [dnanexus/dxWDL#254] opened 2019-05-27 14:02 UTC
@orodeh 

In dxWDL 1.05, I've started getting the following exception during compile:

```
java.lang.IllegalArgumentException: Container ID ProjectName must start with project- or container-
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
at com.dnanexus.DXContainer.checkContainerId(DXContainer.java:35)
at com.dnanexus.DXContainer.<init>(DXContainer.java:49)
at com.dnanexus.DXProject.<init>(DXProject.java:139)
at com.dnanexus.DXProject.getInstance(DXProject.java:154)
at dxWDL.util.Furl$.parseDxFurl(Furl.scala:44)
at dxWDL.util.Furl$.parse(Furl.scala:55)
at dxWDL.util.WomValueAnalysis$.isLocalFile$1(WomValueAnalysis.scala:35)
at dxWDL.util.WomValueAnalysis$.requiresEvaluation(WomValueAnalysis.scala:44)
at dxWDL.util.WomValueAnalysis$.ifConstEval(WomValueAnalysis.scala:91)
at dxWDL.compiler.GenerateIRTask.$anonfun$apply$1(GenerateIRTask.scala:75)
at scala.collection.immutable.List.flatMap(List.scala:335)
at dxWDL.compiler.GenerateIRTask.apply(GenerateIRTask.scala:70)
at dxWDL.compiler.GenerateIR.compileTask2$1(GenerateIR.scala:133)
at dxWDL.compiler.GenerateIR.compileCallable(GenerateIR.scala:140)
at dxWDL.compiler.GenerateIR.$anonfun$apply$5(GenerateIR.scala:218)
at dxWDL.compiler.GenerateIR.$anonfun$apply$5$adapted(GenerateIR.scala:210)
at scala.collection.Iterator.foreach(Iterator.scala:944)
at scala.collection.Iterator.foreach$(Iterator.scala:944)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
at scala.collection.IterableLike.foreach(IterableLike.scala:71)
at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
at dxWDL.compiler.GenerateIR.apply(GenerateIR.scala:210)
at dxWDL.compiler.Top.womToIR(Top.scala:254)
at dxWDL.compiler.Top.apply(Top.scala:308)
at dxWDL.Main$.compile(Main.scala:422)
at dxWDL.Main$.dispatchCommand(Main.scala:740)
at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:797)
at dxWDL.Main$delayedInit$body.apply(Main.scala:13)
at scala.Function0.apply$mcV$sp(Function0.scala:34)
at scala.Function0.apply$mcV$sp$(Function0.scala:34)
at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
at scala.App.$anonfun$main$1$adapted(App.scala:76)
at scala.collection.immutable.List.foreach(List.scala:389)
at scala.App.main(App.scala:76)
at scala.App.main$(App.scala:74)
at dxWDL.Main$.main(Main.scala:13)
at dxWDL.Main.main(Main.scala)
```

In my `extras.json` I have this, which worked up until 1.04:

```
{
    "my_workflow.foo": "dx://ProjectName:/file/path.vcf.gz",
    "my_workflow.bar": "dx://ProjectName:/file/path.vcf.gz.tbi",
    ...
}
```

Is it no longer valid to use the `dx://ProjectName:/file/path.vcf.gz` format and I have to use `dx://proj-xxxx:file-yyyy::ProjectName/file/path.vcf.gz` instead? Or is this a regression?

**Comment by orodeh** [comment] 2019-05-28 15:53
This is a regression. Thanks for reporting.

**Comment by orodeh** [comment] 2019-05-29 17:18
This should be fixed in the upcoming release.

**Comment by orodeh** [comment] 2019-05-31 19:00
Fixed in release [1.06](https://github.com/dnanexus/dxWDL/releases/tag/1.06). Please take a look, and reopen if this doesn't work.

**Comment by pkaleta** [comment] 2019-05-31 23:27
Hi Ohad, I'm still getting the same error in 1.06.

**Comment by orodeh** [comment] 2019-06-01 00:24
Interesting. Can you check release 1.07? I wonder if it is the same bug.

**Comment by pkaleta** [comment] 2019-06-03 09:13
That didn't help, I'm still getting:

```
java.lang.IllegalArgumentException: Container ID ProjectName must start with project- or container-
```

**Comment by pkaleta** [comment] 2019-06-03 09:22
Although now it seems to be getting past the step that resulted in error before:

```
...
Embedding defaults into the IR
Looking for asset-id in dxWDL://releases/1.07
The asset dxWDLrt is from a different project project-F2gg1xj0KFB7BqB65QJG3GY3
Created record-ZZZ pointing to asset dxWDLrt
Found 0 applets and 0 workflows in project-XXX folder=/foo (349 millisec)
Found 5819 applets in project project-XXX (13189 millisec)
Native pass, generate dx:applets and dx:workflows
java.lang.IllegalArgumentException: Container ID ProjectName must start with project- or container-
...
```

Worth noting is the fact that we use `ProjectName` in defaults.json too.

**Comment by orodeh** [comment] 2019-06-03 13:27
@pkaleta Could you include all the details so I can reproduce this problem in my environment? I also need the exact stack trace. 

I have several tests that use file paths as above, and they all work. For example: 
https://github.com/dnanexus/dxWDL/blob/master/test/draft2/files_input.json
https://github.com/dnanexus/dxWDL/blob/master/test/draft2/files.wdl

I am not sure where the problem is occurring.

**Comment by orodeh** [comment] 2019-06-04 20:58
I believe commit (https://github.com/dnanexus/dxWDL/commit/01cbfe2e5d040e4cc797da10e88eeb3be369a747) fixes this bug on master branch.

**Comment by orodeh** [comment] 2019-06-05 19:38
@pkaleta Can you please try out release 1.08 https://github.com/dnanexus/dxWDL/releases/tag/1.08, I believe it fixes this issue, and the download-agent problem you ran into.

**Closed by orodeh** 2019-06-05 19:38 UTC
