### ISSUE TITLE
release 1.06 breaks compile when docker image in project root

### ISSUE THREAD

**Issue by odoublewen** [dnanexus/dxWDL#259] opened 2019-05-31 19:26 UTC
The new 1.06 release breaks my build.  It occurs immediately after the initial `lookupObject` console message.  (See error message at bottom.)

The way I specify docker images in my tasks is:
```
  runtime {
    docker: "dx://docker:my_docker_image-1.0.0"
    ...
  }
```

I also tried adding a root slash (i.e. `dx://docker:/my_docker_image-1.0.0`) but still get the same message.

Not saying this is a bug --  I could well be doing something wrong.

```
java -jar dxWDL-1.06.jar compile workflow.wdl -destination pipelines:/my_workflow-2.0.0
  lookupObject: my_docker_image-1.0.0
[1559330259994] InvalidInput: Expected key "objects[0].folder must be provided when specifying a project" of input to be a nonempty string. Code: 422 Request ID: 1559330259919-627008
InvalidInput: Expected key "objects[0].folder must be provided when specifying a project" of input to be a nonempty string
	at com.dnanexus.exceptions.DXAPIException$ApiExceptionClass$3.generateException(DXAPIException.java:45)
	at com.dnanexus.exceptions.DXAPIException.getInstance(DXAPIException.java:125)
	at com.dnanexus.DXHTTPRequest.requestImpl(DXHTTPRequest.java:428)
	at com.dnanexus.DXHTTPRequest.request(DXHTTPRequest.java:265)
	at com.dnanexus.DXAPI.systemResolveDataObjects(DXAPI.java:27557)
	at dxWDL.dx.DxBulkResolve$.submitRequest(DxBulkResolve.scala:81)
	at dxWDL.dx.DxBulkResolve$.$anonfun$apply$1(DxBulkResolve.scala:167)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at dxWDL.dx.DxBulkResolve$.apply(DxBulkResolve.scala:165)
	at dxWDL.dx.DxPath$.lookupObject(DxPath.scala:75)
	at dxWDL.dx.DxPath$.lookupDxPath(DxPath.scala:91)
	at dxWDL.dx.DxPath$.lookupDxURL(DxPath.scala:112)
	at dxWDL.dx.DxPath$.lookupDxURLFile(DxPath.scala:124)
	at dxWDL.compiler.GenerateIRTask.apply(GenerateIRTask.scala:135)
	at dxWDL.compiler.GenerateIR.compileTask2$1(GenerateIR.scala:134)
	at dxWDL.compiler.GenerateIR.compileCallable(GenerateIR.scala:141)
	at dxWDL.compiler.GenerateIR.$anonfun$apply$5(GenerateIR.scala:219)
	at dxWDL.compiler.GenerateIR.$anonfun$apply$5$adapted(GenerateIR.scala:211)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at dxWDL.compiler.GenerateIR.apply(GenerateIR.scala:211)
	at dxWDL.compiler.Top.womToIR(Top.scala:257)
	at dxWDL.compiler.Top.apply(Top.scala:311)
	at dxWDL.Main$.compile(Main.scala:431)
	at dxWDL.Main$.dispatchCommand(Main.scala:749)
	at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:806)
	at dxWDL.Main$delayedInit$body.apply(Main.scala:14)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at dxWDL.Main$.main(Main.scala:14)
	at dxWDL.Main.main(Main.scala)

make: *** [build] Error 1
```

**Comment by orodeh** [comment] 2019-05-31 20:39
@odoublewen I think the problem is the colon. In the string `dx://docker:my_docker_image-1.0.0`, the colon between `docker` and `my_docker` is throwing the parsing code off. The parser thinks that you mean `project-xxxx:file-yyyy`, which is not the case. 

I will need to fix it, while still recognizing project:file links. Meanwhile, could you remove the colon? For example, rewrite as: dx://docker-my_docker_image-1.0.0`.

**Comment by odoublewen** [comment] 2019-05-31 20:46
Thanks... But I am, in fact, using the colon to distinguish the project from the file.  I.e. I have a project called `docker`, and in it I have a file called `my_docker_image-1.0.0`.

The workflow builds without any problems with dxWDL-1.05.jar

Do I now have to specify the project and objects using their DNAx IDs?

**Comment by orodeh** [comment] 2019-05-31 20:47
It shouldn't be that way.

**Comment by odoublewen** [comment] 2019-05-31 20:57
FYI -- I can fix it by putting my docker images in a folder.  As a test, I made a folder called "foo" and moved my docker images into it.  Now this works, with 1.05 and 1.06:

```
  runtime {
    docker: "dx://docker:/foo/my_docker_image-1.0.0"
    ...
  }
```

**Comment by orodeh** [comment] 2019-05-31 21:11
Thanks, that's a good hint for what is going wrong in the code. I think I can fix it now.

**Comment by orodeh** [comment] 2019-05-31 23:58
Fixed on master.

**Comment by odoublewen** [comment] 2019-07-04 05:35
Sorry to pester you about on this issue again, but I am needing some further clarification about docker images hosted on DNAnexus projects.

I'm pretty sure that, at some point in the past, I was able to build and upload my docker images to a separate project (I called it `docker`) from where I was running my workflow.  But now, when I try to run a compiled dxWDL workflow, I get this error:

```
No accessible project could be found containing the entity file-FY6F7FQ04vY4yg251Q6ZF2vY
```
 
Where `file-FY6F7FQ04vY4yg251Q6ZF2vY` is the docker image that lives in the `docker:` project.

Somehow I thought the compile step was baking the docker image into the applet?  Or???

**Comment by orodeh** [comment] 2019-07-08 18:17
In the way of explanation, the compilation step performs the lookup, and resolves the path to a `project-id:file-id`. This reduces the permissions that the job will require at runtime to access the docker image. 

The problem looks like insufficient permissions, I think. Can you access `file-FY6F7FQ04vY4yg251Q6ZF2vY` from the bash command line, using `dx`?  

```
dx describe file-FY6F7FQ04vY4yg251Q6ZF2vY
```

**Comment by odoublewen** [comment] 2019-07-08 18:44
Yes, I certainly have permissions to access the docker file.    The `dx describe file-FY6F7FQ04vY4yg251Q6ZF2vY` returns the usual details.

Just to be clear about what I am reporting:
1. I have a docker image in project `docker:`.  My DNAnexus user account is an admin on this project.
2. I have a `workflow.wdl` script that refers to the docker image like this:
   ```
   runtime {
     docker: "dx://docker:/foo/my_docker_image-1.0.0"
     ...
   }
   ```
3. I can successfully compile my workflow with `java -jar dxWDL-1.12.jar compile workflow.wdl -destination my_test_project:/my_test_workflow`  (this step was failing when I opened this issue several months ago.)
4. I run the workflow from the same project where I compiled the workflow, like this:
   ```
   $ dx pwd
   my_test_project:/
   $ dx run workflow-FZVjgV804yZKvYPj0zvkzPXq -f ../test/test_input.json
   ```
5. The workflow fails on the step with the docker image, and I see this printed in the log:
   ```
   looking up dx:url dx://file-FY6F7FQ04vY4yg251Q6ZF2vY
   [1562610902033] PermissionDenied: No accessible project could be found containing the entity file-FY6F7FQ04vY4yg251Q6ZF2vY. Code: 401 Request ID: 1562610902922-212287
   PermissionDenied: No accessible project could be found containing the entity file-FY6F7FQ04vY4yg251Q6ZF2vY
   ```

Is the line `looking up dx:url dx://file-FY6F7FQ04vY4yg251Q6ZF2vY` perhaps interesting to you?  Based on your above comments, shouldn't that say `looking up dx:url dx://project-abc123:file-FY6F7FQ04vY4yg251Q6ZF2vY`?

**Comment by odoublewen** [comment] 2019-07-08 18:46
And, again, just to be clear - if I `dx cp` the docker image into `my_test_project:` then the test run without errors...

**Comment by orodeh** [comment] 2019-07-08 19:25
Right. I think you need to add something like this:

```
{
  "default_task_dx_attributes" : {
    "runSpec": {
        "access" : {
          "allProjects": "VIEW",
        }
      }
  }
}
```

and use an extras.json file. See 
https://github.com/dnanexus/dxWDL/blob/master/doc/ExpertOptions.md#setting-dnanexus-specific-attributes-for-tasks.

The is because, by default, the task is run in a job that has access **only** to the current project.

**Comment by odoublewen** [comment] 2019-07-08 19:38
I see -- thank you.

Did this change?  Doesn't really matter but for my sanity :)

I am wondering if perhaps in the past, the compile routine did something automatic like seems to be the case for [private registries](https://github.com/dnanexus/dxWDL/blob/master/doc/ExpertOptions.md#private-registries):

> Compiling a workflow with this configuration sets it to use native docker, and all applets are given the `allProjects: VIEW` permission. This allows them to access the credentials file, even if it is stored on a different project.

Thanks again for the clarification, I will explicitly set the `access` item.

**Comment by orodeh** [comment] 2019-07-08 19:53
It hasn't changed. Please let me know if this fixes the problem though.

**Comment by odoublewen** [comment] 2019-07-08 20:28
Yes, passing the suggested json file via  `-extras` makes this problem go away.

Thanks again.

**Closed** 2019-07-08 20:30 UTC
